<template>
  <div slot="body">
    Multiple node visualizer
    WIP: canvas maybe?
    <hr>
    <div class="flow-modal-data__container">
      <div
        class="flow-modal-data__item"
        v-for="n of nodes"
        :key="'data'+n.id"
      >
        Node: [{{ n.id }}] - {{ n.label }}
        <img
          v-if="activity.nodes[n.id] && activity.nodes[n.id].data && activity.nodes[n.id].data.toString().startsWith('data:image')"
          :src="activity.nodes[n.id].data">
        <p v-else>{{ activity.nodes[n.id] && activity.nodes[n.id].data }}</p>
      </div>
    </div>
  </div>
</template>
<script>
import {mapGetters} from 'vuex'
export default {
  computed: {
    ...mapGetters('flow', ['activity', 'nodeInspect', 'nodeSelection']),
    nodeActivity () {
      return this.activity && this.activity.nodes && this.activity.nodes[this.nodeInspect.id]
    },
    nodes () {
      const nodes = []

      // Extract to array
      for (let k in this.nodeSelection) {
        nodes.push(this.nodeSelection[k])
      }

      return nodes.sort((a, b) => a.y - b.y)
    },
    nodeInspect () {
      return this.$store.state.flow.nodeInspect
    },
    type () {
      if (this.data.startsWith('data:image')) {
        return 'image'
      }
      return 'raw'
    },
    data () {
      // This way we can parse data and show it somehow
      // Could be a base64etc.etc. url generated by server
      // or any plotable data
      return this.nodeActivity && this.nodeActivity.data
    }

  }
}
</script>
<style>
.flow-modal-data__container {
  display:flex;
  flex-flow:row;
  flex-wrap: wrap;
}

.flow-modal-data__item {
  display:flex;
  flex-flow:column;
  flex-basis:25%;
  padding:10px;
}

.flow-modal-data__item img {
  width:100%;
  height:auto;
}
</style>
